name: "Notarize macOS binary"
description: "Signs a binary and submits it for Apple notarization"
inputs:
  binary:
    description: "Path to the binary to notarize"
    required: true
  mac_sign_identity:
    description: "Signing identity"
    required: true
  apple_id:
    description: "Apple ID for notarization"
    required: true
  apple_team_id:
    description: "Apple Team ID"
    required: true
  apple_app_pwd:
    description: "App-specific password for notarization"
    required: true
runs:
  using: "composite"
  steps:
    - name: Sign binary
      shell: bash
      env:
        MAC_SIGN_IDENTITY: ${{ inputs.mac_sign_identity }}
        BINARY: ${{ inputs.binary }}
      run: |
        codesign --force --timestamp --options runtime \
          --sign "$MAC_SIGN_IDENTITY" \
          "$BINARY"

    - name: Notarize binary
      shell: bash
      env:
        BINARY: ${{ inputs.binary }}
        APPLE_ID: ${{ inputs.apple_id }}
        APPLE_TEAM_ID: ${{ inputs.apple_team_id }}
        APPLE_APP_PWD: ${{ inputs.apple_app_pwd }}
      run: |
        ZIP_PATH="${BINARY}.zip"
        zip -j "$ZIP_PATH" "$BINARY"

        xcrun notarytool submit "$ZIP_PATH" \
          --apple-id "$APPLE_ID" \
          --team-id "$APPLE_TEAM_ID" \
          --password "$APPLE_APP_PWD" \
          --wait

        rm -f "$ZIP_PATH"
