name: "Set Version"
description: "Determines the project version from the latest tag."
outputs:
  version:
    description: "Project version (e.g., 1.2.3)"
    value: ${{ steps.setver.outputs.version }}
  stage:
    description: "Development stage or branch name"
    value: ${{ steps.setver.outputs.stage }}
  commit:
    description: "Git commit hash"
    value: ${{ steps.setver.outputs.commit }}
runs:
  using: "composite"
  steps:
    - name: Fetch tags
      run: git fetch --tags --force
      shell: bash

    - name: Set version
      id: setver
      run: |
        # Version from latest tag (strip 'v' prefix)
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
        VERSION="${TAG#v}"
        VERSION="${VERSION#V}"
        VERSION="${VERSION:-}"

        # Stage from current branch
        STAGE=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)
        STAGE="${STAGE:-}"

        # Git commit hash (short)
        COMMIT=$(git rev-parse --short HEAD 2>/dev/null || true)
        COMMIT="${COMMIT:-}"

        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "stage=$STAGE" >> "$GITHUB_OUTPUT"
        echo "commit=$COMMIT" >> "$GITHUB_OUTPUT"

        echo "Version: ${VERSION:-(undefined)}"
        echo "Stage: ${STAGE:-(undefined)}"
        echo "Commit: ${COMMIT:-(undefined)}"
      shell: bash
