name: "Create macOS universal binary"
description: "Creates a macOS universal binary from amd64 and arm64 binaries using lipo"
inputs:
  amd64-binary:
    description: "Path to the amd64 binary"
    required: true
  arm64-binary:
    description: "Path to the arm64 binary"
    required: true
  output:
    description: "Path for the output universal binary"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create universal binary
      shell: bash
      env:
        AMD64_BINARY: ${{ inputs.amd64-binary }}
        ARM64_BINARY: ${{ inputs.arm64-binary }}
        OUTPUT: ${{ inputs.output }}
      run: |
        mkdir -p "$(dirname "$OUTPUT")"
        lipo -create -output "$OUTPUT" "$ARM64_BINARY" "$AMD64_BINARY"
