name: "Semantic Release"
description: "Runs semantic-release and outputs version info"
inputs:
  github-token:
    description: "GitHub token for creating releases"
    required: true
  extra-plugins:
    description: "Space-separated list of additional npx packages to install"
    required: false
    default: ""
outputs:
  released:
    description: "Whether a new version was released"
    value: ${{ steps.check.outputs.released }}
  version:
    description: "The released version number"
    value: ${{ steps.check.outputs.version }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GIT_AUTHOR_NAME: "github-actions[bot]"
        GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
        GIT_COMMITTER_NAME: "github-actions[bot]"
        GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
      shell: bash
      run: |
        EXTRA_PKGS=""
        if [ -n "${{ inputs.extra-plugins }}" ]; then
          for pkg in ${{ inputs.extra-plugins }}; do
            EXTRA_PKGS="$EXTRA_PKGS -p $pkg"
          done
        fi
        npx --yes \
          -p semantic-release@^23.0.0 \
          -p @semantic-release/commit-analyzer@^13.0.0 \
          -p @semantic-release/exec@^6.0.3 \
          -p @semantic-release/github@^10.0.0 \
          -p @semantic-release/release-notes-generator@^14.0.0 \
          -p conventional-changelog-conventionalcommits@^7.0.0 \
          $EXTRA_PKGS \
          semantic-release

    - name: Check for release
      id: check
      shell: bash
      run: |
        if [ -f .release-version ]; then
          VERSION=$(cat .release-version)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "released=true" >> "$GITHUB_OUTPUT"
          echo "Released version: $VERSION"
        else
          echo "released=false" >> "$GITHUB_OUTPUT"
          echo "No new release"
        fi
