name: "Go Test Coverage"
description: "Runs Go tests and generates coverage report"
inputs:
  coverage-threshold:
    description: "Minimum coverage percentage required"
    required: false
    default: "50"
outputs:
  coverage:
    description: "Coverage percentage"
    value: ${{ steps.coverage.outputs.percentage }}
runs:
  using: "composite"
  steps:
    - name: Test
      id: test
      run: go test -v -coverprofile=${{ runner.temp }}/coverage.out ./...
      shell: bash

    - name: Generate HTML coverage report
      run: |
        mkdir -p ${{ runner.temp }}/coverage
        go tool cover -html=${{ runner.temp }}/coverage.out -o ${{ runner.temp }}/coverage/coverage.html
      shell: bash

    - name: Extract coverage percentage
      id: coverage
      run: |
        COVERAGE=$(go tool cover -func=${{ runner.temp }}/coverage.out | grep total | awk '{gsub(/%/, "", $3); print $3}')
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check coverage threshold
      env:
        THRESHOLD: ${{ inputs.coverage-threshold }}
      run: |
        if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
          echo "::error::Coverage ${COVERAGE}% is below ${THRESHOLD}% threshold"
          exit 1
        fi
      shell: bash

    - name: Create badge JSON
      run: |
        mkdir -p ${{ runner.temp }}/badges
        if (( $(echo "$COVERAGE >= 80" | bc -l) )); then
          COLOR="brightgreen"
        elif (( $(echo "$COVERAGE >= 60" | bc -l) )); then
          COLOR="yellow"
        else
          COLOR="red"
        fi
        echo "{\"schemaVersion\":1,\"label\":\"coverage\",\"message\":\"${COVERAGE}%\",\"color\":\"${COLOR}\"}" > ${{ runner.temp }}/badges/coverage.json
      shell: bash

    - name: Upload coverage badge
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: ${{ runner.temp }}/badges/coverage.json

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ runner.temp }}/coverage/coverage.html
