name: "Go Docs"
description: "Generates Go reference documentation with gomarkdoc and uploads as artifact"
runs:
  using: "composite"
  steps:
    - name: Generate Go reference docs
      shell: bash
      run: |
        go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
        mkdir -p docs
        gomarkdoc -u -o docs/index.md ./...

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/
