name: "Import macOS signing certificate"
description: "Imports a base64-encoded PKCS#12 certificate into a temporary keychain"
inputs:
  mac_cert_p12:
    required: true
    description: "Base64-encoded PKCS#12 certificate"
  mac_cert_pwd:
    required: true
    description: "Password for the PKCS#12 certificate"
outputs:
  keychain:
    description: "Path to the created keychain"
    value: ${{ steps.import.outputs.keychain }}
runs:
  using: "composite"
  steps:
    - name: Import certificate
      id: import
      shell: bash
      env:
        MAC_CERT_P12: ${{ inputs.mac_cert_p12 }}
        MAC_CERT_PWD: ${{ inputs.mac_cert_pwd }}
      run: |
        set -euo pipefail
        : "${MAC_CERT_P12:?MAC_CERT_P12 is required}"
        : "${MAC_CERT_PWD:?MAC_CERT_PWD is required}"

        # Use unique keychain name to avoid conflicts
        KEYCHAIN_NAME="build-${GITHUB_RUN_ID}.keychain"
        KEYCHAIN_PATH="${HOME}/Library/Keychains/${KEYCHAIN_NAME}"
        CERT_FILE=$(mktemp)

        # Decode certificate
        echo "$MAC_CERT_P12" | base64 --decode > "$CERT_FILE"

        # Find Homebrew OpenSSL 3 (pre-installed on macos runners)
        BREW_OPENSSL="$(brew --prefix openssl@3 2>/dev/null)/bin/openssl"
        if [ ! -x "$BREW_OPENSSL" ]; then
          echo "::error::Homebrew OpenSSL 3 not found"
          rm -f "$CERT_FILE"
          exit 1
        fi
        echo "Using OpenSSL: $($BREW_OPENSSL version)"

        # Validate certificate
        "$BREW_OPENSSL" pkcs12 -info -in "$CERT_FILE" -passin pass:"$MAC_CERT_PWD" -nokeys -legacy >/dev/null 2>&1 || {
          echo "::error::Certificate is invalid or password is wrong"
          rm -f "$CERT_FILE"
          exit 1
        }

        # Extract cert and key as PEM (avoids PKCS#12 format issues with security import)
        CERT_PEM=$(mktemp)
        KEY_PEM=$(mktemp)
        "$BREW_OPENSSL" pkcs12 -in "$CERT_FILE" -clcerts -nokeys -legacy -passin pass:"$MAC_CERT_PWD" -out "$CERT_PEM"
        "$BREW_OPENSSL" pkcs12 -in "$CERT_FILE" -nocerts -nodes -legacy -passin pass:"$MAC_CERT_PWD" -out "$KEY_PEM"
        rm -f "$CERT_FILE"
        echo "Extracted certificate and key as PEM"

        # Create and configure keychain
        security create-keychain -p "$MAC_CERT_PWD" "$KEYCHAIN_PATH"
        security set-keychain-settings -t 3600 -u "$KEYCHAIN_PATH"
        security list-keychains -s "$KEYCHAIN_PATH" || echo "::warning::Failed to add keychain to search list"
        security default-keychain -s "$KEYCHAIN_PATH"
        security unlock-keychain -p "$MAC_CERT_PWD" "$KEYCHAIN_PATH"

        # Import certificate and key separately as PEM
        security import "$CERT_PEM" -k "$KEYCHAIN_PATH" -T /usr/bin/codesign
        security import "$KEY_PEM" -k "$KEYCHAIN_PATH" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MAC_CERT_PWD" "$KEYCHAIN_PATH"

        # Clean up
        rm -f "$CERT_PEM" "$KEY_PEM"

        # Output keychain path for cleanup
        echo "keychain=$KEYCHAIN_PATH" >> "$GITHUB_OUTPUT"
        echo "Keychain created: $KEYCHAIN_PATH"
