name: "Verify Go Modules"
description: "Downloads and verifies Go module dependencies"
runs:
  using: "composite"
  steps:
    - name: Check tidy
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum || {
          echo "::error::go.mod or go.sum is not tidy. Run 'go mod tidy' locally first."
          exit 1
        }
      shell: bash
    - name: Download
      run: go mod download
      shell: bash
    - name: Verify
      run: go mod verify
      shell: bash
